### PR TITLE
upgraded to 7.17.0.Final

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Review by romartin — APPROVED** [review]

**Review by mareknovotny — CHANGES_REQUESTED** [review]
I think we need to fix http://localhost:8080/drools-wb everywhere too like for jbpm

**Comment by mbiarnes** [comment]
@mareknovotny fixed.
We should look if we still need the distinction between drools.wb and jbpm-workbench, since this is business-central now.

**Comment by mareknovotny** [comment]
@mbiarnes yep, that is probably useless for this use case.

Remember the drools or jbpm is differentiated with a system property for now

**Comment by mbiarnes** [comment]
@mareknovotny hmm - this is only for product - isn't it? what should be done now with this?
Until we don't decide what to do we won't have docker images fro 7.17.0.Final

**Comment by mareknovotny** [comment]
@mbiarnes I doubt it is just for product.

**Pull request merged**
