### PR TITLE
Bumped to 7.6.0.Final

### PR DESCRIPTION
**Pull request by rohit-zabbed**
Bumped up to version 7.6.0. Hopefully these images can be pushed to dockerhub soon.

### CODE REVIEW

**Comment by rohit-zabbed** [comment]
@mbiarnes Can you have a look.

**Comment by mbiarnes** [comment]
@rohit-zabbed did the same on PR #35 (did it yesterday after testing all images)
so I wait until this is approved and then it can be merged - it is basically the same as your PR.
So it's up to @romartin to approve one of both PRs, one will be closed then.

**Review by mbiarnes — APPROVED** [review]
+1

**Comment by romartin** [comment]
@mbiarnes np, I tested your PR as I've just seen this one later, but no matter for me which one to merge, will let you decide and do the merges. Thanks!

**Comment by mbiarnes** [comment]
already bumped up

**Pull request closed without merging**
