### PR TITLE
added role rest-all

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by sashasch** [comment]
Hi,
The question is following:
May be the change should be on dipper lever? On level of Wildfly realm? May be I miss something in your changes, but I have started container:

docker run -p 8080:8080 -p 8001:8001 -d --name drools-wb jboss/drools-workbench-showcase:latest

It took 6.4.0.Final version as expected. I have edited manually the file drools-roles.properties

> > > admin=admin,analyst,kiemgmt,rest-all

Saved it and entered UI -> "User management" section.
"rest-all" indeed added to admin user, but as GROUP, NOT AS ROLE!!!
There are 4 groups, I can attach to admin user "admin", "analyst", "kiemgmt", "plannermgmt" left intact.

**Comment by romartin** [comment]
Hi @mbiarnes, merged  and added into new tag 6.4.0.Final-1: b2e2199a2d0ff8929a89d69135cf695b4a10d35a
Thanks!

**Comment by romartin** [comment]
Hi @sashasch , just saw your comment after closing this PR sorry. If the rest-all appears as a group on the user management area, it means that it's not defined on the webapp deployment descriptor. I have just checked the web.xml for the drools-wb-showcase and there is not rest-all role in the descriptor. 

This behavior is due to Wildfly 8x does not have the concept of groups, only roles, but on the other hand, the Workbench has both groups and roles. So it determines that an entity assigned to a user is a role if it's declared on the webapp deployment descriptor, otherwise it's a group.

Anyway there is not much to do in the docker images side as far  as I see, it's probably missing to add the rest-all role in the web.xml on the different jbpm and drools distributions, can u please open a bug for it and see what others think? Thanks!

**Comment by sashasch** [comment]
Hi Roger,

Thank you much for the detailed explanation and the problem investigation.
Your research only prove my replica, that it should be "deeper level
change". I thought about web.xml, but was not sure about.
I thing, that the role should be added the same way as it was done for the
rest 4 roles, but I have no Idea who is responsible about?

I'm ready to open the bug notification about, but I don't know the correct
place to put it?
Should it be Google groups of Wildfly 8?  Can you provide some link, please?

With Best Regards
            from
                    Volmir Alex !!!

**Comment by romartin** [comment]
HI @sashasch 

Here is a link for a user and group management bug reported, you can use it as example -> https://issues.jboss.org/browse/JBPM-5178

You have to login in issues.jboss.org and create a new ticket like the one above, we will try to fix as soon as possible!  Thanks!

**Comment by mingfang** [comment]
This is still a problem

**Pull request closed without merging**
